name: Build
on: [push,pull_request]

jobs:
  build:
    name: Transpile markdown sources into PDF presentations
    runs-on: nim65s/talks
    steps:
      - uses: actions/checkout@v2
      - run: make
